### ISSUE TITLE
Guzzle and PHP 7.0

### ISSUE THREAD

**Issue by joelbanzatto** [SammyK/LaravelFacebookSdk#156]
I am trying to make it works in a DigitalOcean droplet. I am running NGINX 1.10 with PHP 7.0 and I've got the following error on  my laravel.log:

`[2017-01-19 03:32:14] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /var/www/html/rotaer/vendor/guzzlehttp/guzzle/src/Client.php on line 87 in /var/www/html/rotaer/vendor/guzzlehttp/guzzle/src/Client.php:126
Stack trace:
#0 /var/www/html/rotaer/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('createRequest', 'GET', 'https://graph.f...')
#1 /var/www/html/rotaer/vendor/facebook/graph-sdk/src/Facebook/HttpClients/FacebookGuzzleHttpClient.php(61): GuzzleHttp\Client->__call('createRequest', Array)
#2 /var/www/html/rotaer/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(216): Facebook\HttpClients\FacebookGuzzleHttpClient->send('https://graph.f...', 'GET', '', Array, 60)
#3 /var/www/html/rotaer/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#4 /var/www/html/rotaer/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(338): Facebook\Facebook->sendRequest('GET', '/me?fields=id,n...', Array, 'EAADThB1J2LIBAM...', NULL, 'v2.8')
#5 /var/www/html/rotaer/app/Http/Controllers/APIController.php(171): Facebook\Facebook->get('/me?fields=id,n...', 'EAADThB1J2LIBAM...')
#6 [internal function]: App\Http\Controllers\APIController->login(Object(Illuminate\Http\Request))
#7 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#8 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('login', Array)
#9 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\APIController), 'login')
#10 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#11 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#18 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/html/rotaer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#31 /var/www/html/rotaer/public/index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#32 {main}`

**Comment by joelbanzatto** [comment]
Googling I found this:

http://stackoverflow.com/questions/37161355/argument-3-passed-to-guzzlehttp-clientrequest-must-be-of-the-type-array-str

I installed php7.0-curl extension and the problem is gone.

Thanks!
