### ISSUE TITLE
I got an error when I update(3.4.2 -> 3.5.0).

### ISSUE THREAD

**Issue by pouu69** [SammyK/LaravelFacebookSdk#189]
OS: Mac
laravel version : 5.5.1
php : 7.0

i used command below line     

`composer update sammyk/laravel-facebook-sdk`

so i got an error

````
Fatal error: Uncaught ReflectionException: Class config does not exist in /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('config')
#1 /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('config')
#2 /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('config')
#3 /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('config')
#4 /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('config')
#5 /Users/tubloo/Site/laravel/tyle-lara in /Users/tubloo/Site/laravel/tyle-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
````

why?

**Comment by pouu69** [comment]
I suggested for a new solution.

[https://github.com/SammyK/LaravelFacebookSdk/pull/193](https://github.com/SammyK/LaravelFacebookSdk/pull/193)
